<template>
  <section class="advanced-workspace" v-loading="loading">
    <div class="section-head"><div><span>04 / 批量与智能工作流</span><h2>生产力中心</h2></div><el-button text @click="loadAll"><el-icon><Refresh /></el-icon> 刷新</el-button></div>
    <div class="advanced-grid">
      <article class="advanced-card"><div class="card-title"><el-icon><Files /></el-icon><div><strong>批量处理</strong><small>选择多份文档生成统一摘要</small></div></div><el-select v-model="batchIds" multiple filterable collapse-tags placeholder="选择文档" class="wide"><el-option v-for="doc in documents" :key="doc.id" :label="titleOf(doc)" :value="String(doc.id)" /></el-select><el-button type="primary" plain :loading="batchLoading" @click="runBatchSummary">批量生成摘要</el-button></article>
      <article class="advanced-card"><div class="card-title"><el-icon><DocumentAdd /></el-icon><div><strong>文档模板</strong><small>会议纪要、周报、需求文档</small></div></div><el-select v-model="templateType" class="wide"><el-option label="会议纪要" value="meeting" /><el-option label="项目周报" value="weekly" /><el-option label="需求文档" value="requirement" /><el-option label="项目报告" value="report" /></el-select><el-button type="primary" plain @click="createTemplate">创建模板文档</el-button></article>
      <article class="advanced-card"><div class="card-title"><el-icon><MagicStick /></el-icon><div><strong>AI 改写</strong><small>扩写、压缩、正式化与翻译</small></div></div><el-select v-model="rewriteMode" class="wide"><el-option label="正式商务表达" value="正式商务表达" /><el-option label="精简为要点" value="精简为要点" /><el-option label="扩写为完整说明" value="扩写为完整说明" /><el-option label="翻译为英文" value="翻译为英文" /></el-select><el-button type="primary" plain :loading="rewriteLoading" @click="rewrite">改写当前文本</el-button></article>
      <article class="advanced-card"><div class="card-title"><el-icon><DataAnalysis /></el-icon><div><strong>质量与安全检查</strong><small>结构、重复与敏感信息</small></div></div><div class="quality"><span>标题层级 {{ quality.headings }} 项</span><span>重复段 {{ quality.duplicates }} 处</span><span>风险项 {{ quality.risks }} 个</span></div><el-button plain @click="inspect">生成质量报告</el-button></article>
      <article class="advanced-card"><div class="card-title"><el-icon><Connection /></el-icon><div><strong>多文档分析</strong><small>找出共同主题与冲突点</small></div></div><el-select v-model="analysisIds" multiple filterable collapse-tags placeholder="至少选择两份文档" class="wide"><el-option v-for="doc in documents" :key="doc.id" :label="titleOf(doc)" :value="String(doc.id)" /></el-select><el-button plain :loading="analysisLoading" @click="analyzeMany">生成分析报告</el-button></article>
      <article class="advanced-card"><div class="card-title"><el-icon><Collection /></el-icon><div><strong>知识库索引</strong><small>{{ indexedIds.length }} 份文档已建立索引</small></div></div><el-select v-model="indexId" filterable placeholder="选择文档加入知识库" class="wide"><el-option v-for="doc in documents" :key="doc.id" :label="titleOf(doc)" :value="String(doc.id)" /></el-select><div class="button-pair"><el-button type="primary" plain :loading="indexLoading" @click="indexDocument">加入知识库</el-button><el-button plain @click="removeIndex" :disabled="!indexId">移出索引</el-button></div></article>
    </div>
    <div class="history"><div><strong>任务中心</strong><small>保留本浏览器中的处理记录</small></div><el-empty v-if="history.length===0" description="还没有处理记录" :image-size="48" /><div v-else class="history-list"><div v-for="item in history.slice(0,8)" :key="item.id"><span class="history-dot"></span><strong>{{ item.title }}</strong><small>{{ item.time }}</small><em>{{ item.status }}</em></div></div></div>
    <el-dialog v-model="resultVisible" title="SmartDoc 处理结果" width="620px"><pre class="advanced-result">{{ output }}</pre><template #footer><el-button @click="resultVisible=false">关闭</el-button><el-button type="primary" @click="copyOutput">复制</el-button></template></el-dialog>
  </section>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { ElMessage } from 'element-plus'
import { docApi } from '../../api/document'
import { aiApi } from '../../api/ai'

const props = defineProps({ currentContent: { type: String, default: '' } })
const emit = defineEmits(['apply'])
const documents=ref([]), batchIds=ref([]), analysisIds=ref([]), indexId=ref(''), indexedIds=ref([]), templateType=ref('meeting'), rewriteMode=ref('正式商务表达'), loading=ref(false), batchLoading=ref(false), rewriteLoading=ref(false), analysisLoading=ref(false), indexLoading=ref(false), output=ref(''), resultVisible=ref(false)
const history=ref(JSON.parse(localStorage.getItem('smartdoc_tool_history')||'[]'))
const quality=ref({headings:0,duplicates:0,risks:0})
const titleOf=d=>d?.title||d?.name||'未命名文档'; const data=r=>r?.data??r??{}; const user=()=>localStorage.getItem('userId')
function record(title,status='已完成'){history.value.unshift({id:Date.now()+Math.random(),title,status,time:new Date().toLocaleString()});history.value=history.value.slice(0,30);localStorage.setItem('smartdoc_tool_history',JSON.stringify(history.value))}
async function loadAll(){loading.value=true;try{documents.value=data(await docApi.getUserDocs(user()))||[];indexedIds.value=data(await aiApi.getIndexedDocuments())||[]}catch(e){ElMessage.error('读取工具箱数据失败')}finally{loading.value=false}}
async function contents(ids){return Promise.all(ids.map(async id=>{const d=data(await docApi.getDocDetail(id));return `【${titleOf(d)}】\n${d.content||''}`}))}
function show(text,title='处理完成'){output.value=text;resultVisible.value=true;record(title)}
async function runBatchSummary(){if(!batchIds.value.length)return ElMessage.warning('请选择至少一份文档');batchLoading.value=true;try{const text=(await contents(batchIds.value)).join('\n\n').slice(0,24000);const r=data(await aiApi.summarizeText(text,600));show(r.summary||r.content||JSON.stringify(r),'批量摘要')}catch(e){ElMessage.error('批量处理失败')}finally{batchLoading.value=false}}
async function createTemplate(){const map={meeting:['会议纪要','会议主题：\n会议时间：\n参会人员：\n\n## 核心讨论\n\n## 决策事项\n\n## 待办事项\n| 事项 | 负责人 | 截止时间 |\n| --- | --- | --- |'],weekly:['项目周报','本周完成：\n\n下周计划：\n\n风险与阻塞：\n\n需要协调支持：'],requirement:['需求文档','## 背景与目标\n\n## 用户场景\n\n## 功能需求\n\n## 验收标准\n\n## 风险与边界'],report:['项目报告','## 项目概述\n\n## 关键成果\n\n## 数据与分析\n\n## 问题与改进\n\n## 后续计划']}[templateType.value];try{const r=data(await docApi.createDoc({title:map[0],content:map[1],category:'template'}));await loadAll();show(map[1],'模板已创建');emit('apply',map[1]);indexId.value=String(r.id||'')}catch(e){ElMessage.error('模板创建失败')}}
async function rewrite(){if(!props.currentContent.trim())return ElMessage.warning('请先在上方选择或输入文本');rewriteLoading.value=true;try{const r=data(await aiApi.executeAgent({task:`请将以下文本${rewriteMode.value}。只输出处理后的正文：\n\n${props.currentContent}`,context:{source:'toolbox-rewrite'}}));const text=r.finalAnswer||r.answer||r.content||JSON.stringify(r);show(text,'AI 改写');emit('apply',text)}catch(e){ElMessage.error('AI 改写失败')}finally{rewriteLoading.value=false}}
function inspect(){const lines=props.currentContent.split('\n').filter(Boolean), seen=new Set();let dup=0;lines.forEach(l=>{const k=l.replace(/\s/g,'');if(seen.has(k))dup++;seen.add(k)});quality.value={headings:lines.filter(l=>/^#|^第[一二三四五六七八九十\d]+/.test(l)).length,duplicates:dup,risks:(props.currentContent.match(/1[3-9]\d{9}|[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g)||[]).length};show(`文档质量报告\n\n标题层级：${quality.value.headings} 项\n重复段落：${dup} 处\n敏感信息风险：${quality.value.risks} 项\n总字数：${props.currentContent.length} 字`,'质量检查')}
async function analyzeMany(){if(analysisIds.value.length<2)return ElMessage.warning('至少选择两份文档');analysisLoading.value=true;try{const text=(await contents(analysisIds.value)).join('\n\n').slice(0,24000);const r=data(await aiApi.executeAgent({task:`分析以下多份文档，输出：共同主题、相互矛盾或不一致点、可统一的结论。\n\n${text}`,context:{source:'toolbox-multi-analysis'}}));show(r.finalAnswer||r.answer||r.content||JSON.stringify(r),'多文档分析')}catch(e){ElMessage.error('多文档分析失败')}finally{analysisLoading.value=false}}
async function indexDocument(){if(!indexId.value)return ElMessage.warning('请选择一份文档');indexLoading.value=true;try{const d=data(await docApi.getDocDetail(indexId.value));if(!d.content)return ElMessage.warning('该文档尚无正文，请先完成 OCR 或录入内容');await aiApi.indexWithSegment(indexId.value,d.content,'AUTO');await loadAll();record('知识库索引');ElMessage.success('已加入知识库')}catch(e){ElMessage.error('索引失败')}finally{indexLoading.value=false}}
async function removeIndex(){try{await aiApi.removeIndexedDocument(indexId.value);await loadAll();record('移出知识库');ElMessage.success('已移出知识库')}catch(e){ElMessage.error('移除失败')}}
async function copyOutput(){try{await navigator.clipboard.writeText(output.value);ElMessage.success('已复制')}catch(e){ElMessage.warning('请手动复制')}}
onMounted(loadAll)
</script>

<style scoped>
.advanced-workspace{max-width:1500px;margin:22px auto 0;padding:22px;border:1px solid #ebe5ea;border-radius:20px;background:#fff;box-shadow:0 8px 28px #7a6d8a0b}.section-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:16px}.section-head span{font-size:10px;letter-spacing:1.4px;font-weight:700;color:#847a9a}.section-head h2{font-size:18px;margin:4px 0 0;color:#4b4655}.advanced-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.advanced-card{padding:14px;border-radius:15px;background:#fbfaf9;border:1px solid #f0ebee;display:flex;flex-direction:column;gap:10px}.card-title{display:flex;gap:8px;align-items:center}.card-title>.el-icon{color:#7b6a9c;background:#eeeaf6;padding:7px;border-radius:9px;font-size:16px}.card-title div{display:flex;flex-direction:column;gap:2px}.card-title strong{font-size:13px;color:#5c5463}.card-title small{font-size:10px;color:#a098a8}.wide{width:100%}.advanced-card .el-button{align-self:flex-start}.button-pair{display:flex;gap:6px}.quality{display:flex;gap:5px;flex-wrap:wrap}.quality span{font-size:10px;color:#807787;background:#f3eff4;border-radius:6px;padding:5px}.history{margin-top:14px;padding-top:14px;border-top:1px dashed #e6dfe8;display:flex;justify-content:space-between;gap:18px}.history>div:first-child{display:flex;flex-direction:column;gap:3px}.history strong{font-size:13px;color:#5c5463}.history small{font-size:10px;color:#a098a8}.history-list{flex:1;display:grid;grid-template-columns:repeat(2,1fr);gap:6px}.history-list>div{display:flex;align-items:center;gap:6px;padding:6px 9px;border-radius:8px;background:#faf8fb;font-size:11px}.history-dot{width:5px;height:5px;border-radius:50%;background:#7d9d72}.history-list strong{font-weight:500;flex:1}.history-list em{font-style:normal;color:#77906f;font-size:10px}.advanced-result{white-space:pre-wrap;word-break:break-word;max-height:55vh;overflow:auto;font:13px/1.7 "Microsoft YaHei",sans-serif;color:#5d5663}@media(max-width:900px){.advanced-grid{grid-template-columns:1fr 1fr}}@media(max-width:600px){.advanced-grid,.history-list{grid-template-columns:1fr}.history{flex-direction:column}}
</style>
